export const bookNames = {
  "Genèse": "Genèse",
  "Gen": "Genèse",
  "Gn": "Genèse",

  "Exode": "Exode",
  "Exo": "Exode",
  "Ex": "Exode",

  "Lévitique": "Lévitique",
  "Lev": "Lévitique",
  "Lv": "Lévitique",

  "Nombres": "Nombres",
  "Nom": "Nombres",
  "Nb": "Nombres",
  "Nbs": "Nombres",

  "Deutéronome": "Deutéronome",
  "Deut": "Deutéronome",
  "De": "Deutéronome",
  "Dt": "Deutéronome",

  "Josué": "Josué",
  "Jos": "Josué",
  "Jo": "Josué",
  "Js": "Josué",

  "Juges": "Juges",
  "Jug": "Juges",
  "Ju": "Juges",

  "1 Samuel": "Samuel",
  "1 Sam": "Samuel",
  "1 Sa": "Samuel",
  "1 S": "Samuel",
  "1Sa": "Samuel",
  "1Sm": "Samuel",
  "1S": "Samuel",

  "2 Samuel": "Samuel",
  "2 Sam": "Samuel",
  "2 Sa": "Samuel",
  "2 S": "Samuel",
  "2Sa": "Samuel",
  "2Sm": "Samuel",
  "2S": "Samuel",

  "1 Rois": "Rois",
  "1 Ro": "Rois",
  "1 R": "Rois",
  "1Rois": "Rois",
  "1Ro": "Rois",
  "1R": "Rois",

  "2 Rois": "Rois",
  "2 Ro": "Rois",
  "2 R": "Rois",
  "2Rois": "Rois",
  "2Ro": "Rois",
  "2R": "Rois",

  "Ésaïe": "Ésaïe",
  "Jérémie": "Jérémie",
  "Ezékiel": "Ezékiel",
  "Osée": "Osée",
  "Joël": "Joël",
  "Amos": "Amos",
  "Abdias": "Abdias",
  "Jonas": "Jonas",
  "Michée": "Michée",
  "Nahum": "Nahum",
  "Habaquq": "Habaquq",
  "Sophonie": "Sophonie",
  "Aggée": "Aggée",
  "Zacharie": "Zacharie",
  "Malachie": "Malachie",
  "Psaumes": "Psaumes",
  "Proverbes": "Proverbes",
  "Job": "Job",
  "Cantique des cantiques": "cantiques",
  "Ruth": "Ruth",
  "Lamentations": "Lamentations",
  "Ecclésiastes": "Ecclésiastes",
  "Esther": "Esther",
  "Daniel": "Daniel",
  "Esdras": "Esdras",
  "Néhémie": "Néhémie",
  "1 Chroniques": "Chroniques",
  "2 Chroniques": "Chroniques",

  "Matthieu": "Matthieu",
  "Marc": "Marc",
  "Luc": "Luc",
  "Jean": "Jean",
  "Actes": "Actes",
  "Romains": "Romains",
  "1 Corinthiens": "Corinthiens",
  "2 Corinthiens": "Corinthiens",
  "Galates": "Galates",
  "Éphésiens": "Éphésiens",
  "Philippiens": "Philippiens",
  "Colossiens": "Colossiens",
  "1 Thessaloniciens": "Thessaloniciens",
  "2 Thessaloniciens": "Thessaloniciens",
  "1 Timothée": "Timothée",
  "2 Timothée": "Timothée",
  "Tite": "Tite",
  "Philémon": "Philémon",
  "Hébreux": "Hébreux",
  "Jacques": "Jacques",
  "1 Pierre": "Pierre",
  "2 Pierre": "Pierre",
  "1 Jean": "Jean",
  "2 Jean": "Jean",
  "3 Jean": "Jean",
  "Jude": "Jude",
  "Apocalypse": "Apocalypse"
}


export const bookChapters = {
  "Genèse": 50,
  "Exode": 40,
  "Lévitique": 27,
  "Nombres": 36,
  "Deutéronome": 34,
  "Josué": 24,
  "Juges": 21,
  "1 Samuel": 31,
  "2 Samuel": 24,
  "1 Rois": 22,
  "2 Rois": 25,
  "Ésaïe": 66,
  "Jérémie": 52,
  "Ezékiel": 48,
  "Osée": 14,
  "Joël": 3,
  "Amos": 9,
  "Abdias": 1,
  "Jonas": 4,
  "Michée": 7,
  "Nahum": 3,
  "Habaquq": 3,
  "Sophonie": 3,
  "Aggée": 2,
  "Zacharie": 14,
  "Malachie": 4,
  "Psaumes": 150,
  "Proverbes": 31,
  "Job": 42,
  "Cantique des cantiques": 8,
  "Ruth": 4,
  "Lamentations": 5,
  "Ecclésiastes": 12,
  "Esther": 10,
  "Daniel": 12,
  "Esdras": 10,
  "Néhémie": 13,
  "1 Chroniques": 29,
  "2 Chroniques": 36,

  // NT
  "Matthieu": 28,
  "Marc": 16,
  "Luc": 24,
  "Jean": 21,
  "Actes": 28,
  "Romains": 16,
  "1 Corinthiens": 16,
  "2 Corinthiens": 13,
  "Galates": 6,
  "Éphésiens": 6,
  "Philippiens": 4,
  "Colossiens": 4,
  "1 Thessaloniciens": 5,
  "2 Thessaloniciens": 3,
  "1 Timothée": 6,
  "2 Timothée": 4,
  "Tite": 3,
  "Philémon": 1,
  "Hébreux": 13,
  "Jacques": 5,
  "1 Pierre": 5,
  "2 Pierre": 3,
  "1 Jean": 5,
  "2 Jean": 1,
  "3 Jean": 1,
  "Jude": 1,
  "Apocalypse": 22
}
