export const bookNames = {
  "Genèse": "Genèse",
  "Gen": "Genèse",
  "Gn": "Genèse",

  "Exode": "Exode",
  "Exo": "Exode",
  "Ex": "Exode",

  "Lévitique": "Lévitique",
  "Lev": "Lévitique",
  "Lv": "Lévitique",

  "Nombres": "Nombres",
  "Nom": "Nombres",
  "Nb": "Nombres",
  "Nbs": "Nombres",

  "Deutéronome": "Deutéronome",
  "Deut": "Deutéronome",
  "De": "Deutéronome",
  "Dt": "Deutéronome",

  "Josué": "Josué",
  "Jos": "Josué",
  "Jo": "Josué",
  "Js": "Josué",

  "Juges": "Juges",
  "Jug": "Juges",
  "Ju": "Juges",

  "1 Samuel": "1Samuel",
  "1 Sam": "1Samuel",
  "1 Sa": "1Samuel",
  "1 S": "1Samuel",
  "1Samuel": "1Samuel",
  "1Sa": "1Samuel",
  "1Sm": "1Samuel",
  "1S": "1Samuel",

  "2 Samuel": "2Samuel",
  "2 Sam": "2Samuel",
  "2 Sa": "2Samuel",
  "2 S": "2Samuel",
  "2Samuel": "2Samuel",
  "2Sa": "2Samuel",
  "2Sm": "2Samuel",
  "2S": "2Samuel",

  "1 Rois": "1Rois",
  "1 Ro": "1Rois",
  "1 R": "1Rois",
  "1Rois": "1Rois",
  "1Ro": "1Rois",
  "1R": "1Rois",

  "2 Rois": "2Rois",
  "2 Ro": "2Rois",
  "2 R": "2Rois",
  "2Rois": "2Rois",
  "2Ro": "2Rois",
  "2R": "2Rois",

  "Ésaïe": "Ésaïe",
  "Ésa": "Ésaïe",
  "Esa": "Ésaïe",
  "Es": "Ésaïe",

  "Jérémie": "Jérémie",
  "Jér": "Jérémie",
  "Jé": "Jérémie",
  "Jer": "Jérémie",
  "Je": "Jérémie",
  "Jm": "Jérémie",

  "Ezékiel": "Ezékiel",
  "Ezék": "Ezékiel",
  "Ezek": "Ezékiel",
  "Ez": "Ezékiel",

  "Osée": "Osée",
  "Osee": "Osée",
  "Ose": "Osée",
  "Os": "Osée",

  "Joël": "Joël",
  "Joel": "Joël",
  "Jo": "Joël",
  "Jl": "Joël",

  "Amos": "Amos",
  "Amo": "Amos",
  "Am": "Amos",

  "Abdias": "Abdias",
  "Abd": "Abdias",
  "Ab": "Abdias",

  "Jonas": "Jonas",
  "Jon": "Jonas",
  "Jo": "Jonas",

  "Michée": "Michée",
  "Michee": "Michée",
  "Mich": "Michée",
  "Mi": "Michée",
  "Mi": "Michée",

  "Nahum": "Nahum",
  "Nah": "Nahum",
  "Nm": "Nahum",

  "Habaquq": "Habaquq",
  "Hab": "Habaquq",
  "Ha": "Habaquq",

  "Sophonie": "Sophonie",
  "Soph": "Sophonie",
  "So": "Sophonie",

  "Aggée": "Aggée",
  "Aggee": "Aggée",
  "Agg": "Aggée",
  "Ag": "Aggée",

  "Zacharie": "Zacharie",
  "Zach": "Zacharie",
  "Zac": "Zacharie",
  "Za": "Zacharie",

  "Malachie": "Malachie",
  "Mal": "Malachie",
  "Ma": "Malachie",

  "Psaumes": "Psaumes",
  "Psa": "Psaumes",
  "Pss": "Psaumes",

  "Proverbes": "Proverbes",
  "Prov": "Proverbes",
  "Pr": "Proverbes",

  "Job": "Job",
  "Jb": "Job",

  "Cantique des cantiques": "Cantiques",
  "Cantiques": "Cantiques",
  "Cantique": "Cantiques",
  "Ca": "Cantiques",
  "Ccd": "Cantiques",

  "Ruth": "Ruth",
  "Rut": "Ruth",
  "Ru": "Ruth",

  "Lamentations": "Lamentations",
  "Lam": "Lamentations",
  "Lm": "Lamentations",

  "Ecclésiastes": "Ecclésiastes",
  "Ecclesiastes": "Ecclésiastes",
  "Eccl": "Ecclésiastes",
  "Ecc": "Ecclésiastes",
  "Ec": "Ecclésiastes",

  "Esther": "Esther",
  "Est": "Esther",
  "Es": "Esther",

  "Daniel": "Daniel",
  "Dan": "Daniel",
  "Da": "Daniel",

  "Esdras": "Esdras",
  "Esd": "Esdras",
  "Ed": "Esdras",

  "Néhémie": "Néhémie",
  "Nehemie": "Néhémie",
  "Neh": "Néhémie",
  "Ne": "Néhémie",

  "1 Chroniques": "1Chroniques",
  "1 Chr": "1Chroniques",
  "1 Ch": "1Chroniques",
  "1Chroniques": "1Chroniques",
  "1Chr": "1Chroniques",
  "1Ch": "1Chroniques",

  "2 Chroniques": "2Chroniques",
  "2 Chr": "2Chroniques",
  "2 Ch": "2Chroniques",
  "2Chroniques": "2Chroniques",
  "2Chr": "2Chroniques",
  "2Ch": "2Chroniques",

  "Matthieu": "Matthieu",
  "Matt": "Matthieu",
  "Mat": "Matthieu",
  "Mt": "Matthieu",

  "Marc": "Marc",
  "Mar": "Marc",
  "Mc": "Marc",

  "Luc": "Luc",
  "Lu": "Luc",
  "Lc": "Luc",

  "Jean": "Jean",
  "Jea": "Jean",
  "Jn": "Jean",

  "Actes": "Actes",
  "Act": "Actes",
  "Ac": "Actes",

  "Romains": "Romains",
  "Rom": "Romains",
  "Rm": "Romains",

  "1 Corinthiens": "1Corinthiens",
  "1Corinthiens": "1Corinthiens",
  "1 Cor": "1Corinthiens",
  "1Cor": "1Corinthiens",
  "1 Co": "1Corinthiens",
  "1Co": "1Corinthiens",

  "2 Corinthiens": "2Corinthiens",
  "2Corinthiens": "2Corinthiens",
  "2 Cor": "2Corinthiens",
  "2Cor": "2Corinthiens",
  "2 Co": "2Corinthiens",
  "2Co": "2Corinthiens",

  "Galates": "Galates",
  "Gal": "Galates",
  "Ga": "Galates",
  "Gl": "Galates",

  "Éphésiens": "Éphésiens",
  "Ephesiens": "Éphésiens",
  "Eph": "Éphésiens",
  "Ep": "Éphésiens",

  "Philippiens": "Philippiens",
  "Phil": "Philippiens",
  "Phi": "Philippiens",
  "Ph": "Philippiens",
  "Pl": "Philippiens",

  "Colossiens": "Colossiens",
  "Colo": "Colossiens",
  "Col": "Colossiens",
  "Cl": "Colossiens",
  "Co": "Colossiens",

  "1 Thessaloniciens": "1Thessaloniciens",
  "1 Thess": "1Thessaloniciens",
  "1 Th": "1Thessaloniciens",
  "1Th": "1Thessaloniciens",

  "2 Thessaloniciens": "2Thessaloniciens",
  "2 Thess": "2Thessaloniciens",
  "2 Th": "2Thessaloniciens",
  "2Th": "2Thessaloniciens",

  "1 Timothée": "1Timothée",
  "1 Tim": "1Timothée",
  "1 Tm": "1Timothée",
  "1Tm": "1Timothée",

  "2 Timothée": "2Timothée",
  "2 Tim": "2Timothée",
  "2 Tm": "2Timothée",
  "2Tm": "2Timothée",

  "Tite": "Tite",
  "Tit": "Tite",
  "Ti": "Tite",
  "Tt": "Tite",

  "Philémon": "Philémon",
  "Philemon": "Philémon",
  "Phil": "Philémon",
  "Plm": "Philémon",
  "Pm": "Philémon",
  "Pl": "Philémon",

  "Hébreux": "Hébreux",
  "Hebreux": "Hébreux",
  "Héb": "Hébreux",
  "Heb": "Hébreux",
  "Hb": "Hébreux",

  "Jacques": "Jacques",
  "Jac": "Jacques",
  "Ja": "Jacques",
  "Jc": "Jacques",
  "Jq": "Jacques",

  "1 Pierre": "1Pierre",
  "1 Pie": "1Pierre",
  "1 Pi": "1Pierre",
  "1Pierre": "1Pierre",
  "1Pie": "1Pierre",
  "1Pi": "1Pierre",

  "2 Pierre": "2Pierre",
  "2 Pie": "2Pierre",
  "2 Pi": "2Pierre",
  "2Pierre": "2Pierre",
  "2Pie": "2Pierre",
  "2Pi": "2Pierre",

  "1 Jean": "1Jean",
  "1 Jn": "1Jean",
  "1Jean": "1Jean",
  "1Jn": "1Jean",

  "2 Jean": "2Jean",
  "2 Jn": "2Jean",
  "2Jean": "2Jean",
  "2Jn": "2Jean",

  "3 Jean": "3Jean",
  "3 Jn": "3Jean",
  "3Jean": "3Jean",
  "3Jn": "3Jean",

  "Jude": "Jude",
  "Jud": "Jude",
  "Ju": "Jude",
  "Jd": "Jude",

  "Apocalypse": "Apocalypse",
  "Apoc": "Apocalypse",
  "Apo": "Apocalypse",
  "Ap": "Apocalypse",
}


export const bookChapters = {
  "Genèse": 50,
  "Exode": 40,
  "Lévitique": 27,
  "Nombres": 36,
  "Deutéronome": 34,
  "Josué": 24,
  "Juges": 21,
  "1Samuel": 31,
  "2Samuel": 24,
  "1Rois": 22,
  "2Rois": 25,
  "Ésaïe": 66,
  "Jérémie": 52,
  "Ezékiel": 48,
  "Osée": 14,
  "Joël": 3,
  "Amos": 9,
  "Abdias": 1,
  "Jonas": 4,
  "Michée": 7,
  "Nahum": 3,
  "Habaquq": 3,
  "Sophonie": 3,
  "Aggée": 2,
  "Zacharie": 14,
  "Malachie": 4,
  "Psaumes": 150,
  "Proverbes": 31,
  "Job": 42,
  "Cantique des cantiques": 8,
  "Ruth": 4,
  "Lamentations": 5,
  "Ecclésiastes": 12,
  "Esther": 10,
  "Daniel": 12,
  "Esdras": 10,
  "Néhémie": 13,
  "1Chroniques": 29,
  "2Chroniques": 36,

  // NT
  "Matthieu": 28,
  "Marc": 16,
  "Luc": 24,
  "Jean": 21,
  "Actes": 28,
  "Romains": 16,
  "1Corinthiens": 16,
  "2Corinthiens": 13,
  "Galates": 6,
  "Éphésiens": 6,
  "Philippiens": 4,
  "Colossiens": 4,
  "1Thessaloniciens": 5,
  "2Thessaloniciens": 3,
  "1Timothée": 6,
  "2Timothée": 4,
  "Tite": 3,
  "Philémon": 1,
  "Hébreux": 13,
  "Jacques": 5,
  "1Pierre": 5,
  "2Pierre": 3,
  "1Jean": 5,
  "2Jean": 1,
  "3Jean": 1,
  "Jude": 1,
  "Apocalypse": 22
}
