import type { BookName } from '@/types'

export const books = [
  // AT
  'Genèse',
  'Exode',
  'Lévitique',
  'Nombres',
  'Deutéronome',
  'Josué',
  'Juges',
  '1Samuel',
  '2Samuel',
  '1Rois',
  '2Rois',
  'Ésaïe',
  'Jérémie',
  'Ezékiel',
  'Osée',
  'Joël',
  'Amos',
  'Abdias',
  'Jonas',
  'Michée',
  'Nahum',
  'Habaquq',
  'Sophonie',
  'Aggée',
  'Zacharie',
  'Malachie',
  'Psaumes',
  'Proverbes',
  'Job',
  'Cantiques',
  'Ruth',
  'Lamentations',
  'Ecclésiastes',
  'Esther',
  'Daniel',
  'Esdras',
  'Néhémie',
  '1Chroniques',
  '2Chroniques',

  // NT
  'Matthieu',
  'Marc',
  'Luc',
  'Jean',
  'Actes',
  'Romains',
  '1Corinthiens',
  '2Corinthiens',
  'Galates',
  'Éphésiens',
  'Philippiens',
  'Colossiens',
  '1Thessaloniciens',
  '2Thessaloniciens',
  '1Timothée',
  '2Timothée',
  'Tite',
  'Philémon',
  'Hébreux',
  'Jacques',
  '1Pierre',
  '2Pierre',
  '1Jean',
  '2Jean',
  '3Jean',
  'Jude',
  'Apocalypse'
] as const

export const bookMeta: Record<BookName, { nbChap: number; label: string }> = {
  // AT
  Genèse: { nbChap: 50, label: 'Gn' },
  Exode: { nbChap: 40, label: 'Ex' },
  Lévitique: { nbChap: 27, label: 'Lv' },
  Nombres: { nbChap: 36, label: 'Nb' },
  Deutéronome: { nbChap: 34, label: '' },
  Josué: { nbChap: 24, label: 'Dt' },
  Juges: { nbChap: 21, label: 'Jg' },
  '1Samuel': { nbChap: 31, label: '1S' },
  '2Samuel': { nbChap: 24, label: '2S' },
  '1Rois': { nbChap: 22, label: '1R' },
  '2Rois': { nbChap: 25, label: '2R' },
  Ésaïe: { nbChap: 66, label: 'És' },
  Jérémie: { nbChap: 52, label: 'Jr' },
  Ezékiel: { nbChap: 48, label: 'Éz' },
  Osée: { nbChap: 14, label: 'Os' },
  Joël: { nbChap: 3, label: 'Jl' },
  Amos: { nbChap: 9, label: 'Am' },
  Abdias: { nbChap: 1, label: 'Ab' },
  Jonas: { nbChap: 4, label: 'Jon' },
  Michée: { nbChap: 7, label: 'Mi' },
  Nahum: { nbChap: 3, label: 'Na' },
  Habaquq: { nbChap: 3, label: 'Ha' },
  Sophonie: { nbChap: 3, label: 'So' },
  Aggée: { nbChap: 2, label: 'Ag' },
  Zacharie: { nbChap: 14, label: 'Za' },
  Malachie: { nbChap: 4, label: 'Ma' },
  Psaumes: { nbChap: 150, label: 'Ps' },
  Proverbes: { nbChap: 31, label: 'Pr' },
  Job: { nbChap: 42, label: 'Jb' },
  Cantiques: { nbChap: 8, label: 'Ct' },
  Ruth: { nbChap: 4, label: 'Rt' },
  Lamentations: { nbChap: 5, label: 'Lm' },
  Ecclésiastes: { nbChap: 12, label: 'Ec' },
  Esther: { nbChap: 10, label: 'Est' },
  Daniel: { nbChap: 12, label: 'Dn' },
  Esdras: { nbChap: 10, label: 'Esd' },
  Néhémie: { nbChap: 13, label: 'Né' },
  '1Chroniques': { nbChap: 29, label: '1Ch' },
  '2Chroniques': { nbChap: 36, label: '2Ch' },

  // NT
  Matthieu: { nbChap: 28, label: 'Mt' },
  Marc: { nbChap: 16, label: 'Mc' },
  Luc: { nbChap: 24, label: 'Lc' },
  Jean: { nbChap: 21, label: 'Jn' },
  Actes: { nbChap: 28, label: 'Ac' },
  Romains: { nbChap: 16, label: 'Rm' },
  '1Corinthiens': { nbChap: 16, label: '1Co' },
  '2Corinthiens': { nbChap: 13, label: '2Co' },
  Galates: { nbChap: 6, label: 'Ga' },
  Éphésiens: { nbChap: 6, label: 'Ép' },
  Philippiens: { nbChap: 4, label: 'Ph' },
  Colossiens: { nbChap: 4, label: 'Col' },
  '1Thessaloniciens': { nbChap: 5, label: '1Th' },
  '2Thessaloniciens': { nbChap: 3, label: '2Th' },
  '1Timothée': { nbChap: 6, label: '1Tm' },
  '2Timothée': { nbChap: 4, label: '2Tm' },
  Tite: { nbChap: 3, label: 'Tt' },
  Philémon: { nbChap: 1, label: 'Phl' },
  Hébreux: { nbChap: 13, label: 'Hb' },
  Jacques: { nbChap: 5, label: 'Jc' },
  '1Pierre': { nbChap: 5, label: '1Pi' },
  '2Pierre': { nbChap: 3, label: '2Pi' },
  '1Jean': { nbChap: 5, label: '1Jn' },
  '2Jean': { nbChap: 1, label: '2Jn' },
  '3Jean': { nbChap: 1, label: '3Jn' },
  Jude: { nbChap: 1, label: 'Jd' },
  Apocalypse: { nbChap: 22, label: 'Ap' },
} as const

// TODO: Needs a better name
export const bookNames: Record<string, BookName> = {
  genèse: 'Genèse',
  genese: 'Genèse',
  gen: 'Genèse',
  gn: 'Genèse',

  exode: 'Exode',
  exo: 'Exode',
  ex: 'Exode',

  lévitique: 'Lévitique',
  levitique: 'Lévitique',
  lev: 'Lévitique',
  lv: 'Lévitique',

  nombres: 'Nombres',
  nom: 'Nombres',
  nb: 'Nombres',
  nbs: 'Nombres',

  deutéronome: 'Deutéronome',
  deuteronome: 'Deutéronome',
  deut: 'Deutéronome',
  de: 'Deutéronome',
  dt: 'Deutéronome',

  josué: 'Josué',
  josue: 'Josué',
  jos: 'Josué',
  js: 'Josué',

  juges: 'Juges',
  jug: 'Juges',

  '1 samuel': '1Samuel',
  '1 sam': '1Samuel',
  '1 sa': '1Samuel',
  '1 s': '1Samuel',
  '1samuel': '1Samuel',
  '1sa': '1Samuel',
  '1sm': '1Samuel',
  '1s': '1Samuel',

  '2 samuel': '2Samuel',
  '2 sam': '2Samuel',
  '2 sa': '2Samuel',
  '2 s': '2Samuel',
  '2samuel': '2Samuel',
  '2sa': '2Samuel',
  '2sm': '2Samuel',
  '2s': '2Samuel',

  '1 rois': '1Rois',
  '1 ro': '1Rois',
  '1 r': '1Rois',
  '1rois': '1Rois',
  '1ro': '1Rois',
  '1r': '1Rois',

  '2 rois': '2Rois',
  '2 ro': '2Rois',
  '2 r': '2Rois',
  '2rois': '2Rois',
  '2ro': '2Rois',
  '2r': '2Rois',

  ésaïe: 'Ésaïe',
  esaie: 'Ésaïe',
  ésaie: 'Ésaïe',
  ésa: 'Ésaïe',
  esa: 'Ésaïe',
  es: 'Ésaïe',

  jérémie: 'Jérémie',
  jeremie: 'Jérémie',
  jér: 'Jérémie',
  jé: 'Jérémie',
  jer: 'Jérémie',
  je: 'Jérémie',
  jm: 'Jérémie',

  ezékiel: 'Ezékiel',
  ezekiel: 'Ezékiel',
  ezék: 'Ezékiel',
  ezek: 'Ezékiel',
  ez: 'Ezékiel',

  osée: 'Osée',
  osee: 'Osée',
  ose: 'Osée',
  os: 'Osée',

  joël: 'Joël',
  joel: 'Joël',
  jo: 'Joël',
  jl: 'Joël',

  amos: 'Amos',
  amo: 'Amos',
  am: 'Amos',

  abdias: 'Abdias',
  abd: 'Abdias',
  ab: 'Abdias',

  jonas: 'Jonas',
  jon: 'Jonas',

  michée: 'Michée',
  michee: 'Michée',
  mich: 'Michée',
  mi: 'Michée',

  nahum: 'Nahum',
  nah: 'Nahum',
  nm: 'Nahum',

  habaquq: 'Habaquq',
  hab: 'Habaquq',
  ha: 'Habaquq',

  sophonie: 'Sophonie',
  soph: 'Sophonie',
  so: 'Sophonie',

  aggée: 'Aggée',
  aggee: 'Aggée',
  agg: 'Aggée',
  ag: 'Aggée',

  zacharie: 'Zacharie',
  zach: 'Zacharie',
  zac: 'Zacharie',
  za: 'Zacharie',

  malachie: 'Malachie',
  mal: 'Malachie',
  ma: 'Malachie',

  psaumes: 'Psaumes',
  psa: 'Psaumes',
  pss: 'Psaumes',

  proverbes: 'Proverbes',
  prov: 'Proverbes',
  pr: 'Proverbes',

  job: 'Job',
  jb: 'Job',

  'cantique des cantiques': 'Cantiques',
  cantiques: 'Cantiques',
  cantique: 'Cantiques',
  ca: 'Cantiques',
  ct: 'Cantiques',
  ccd: 'Cantiques',

  ruth: 'Ruth',
  rut: 'Ruth',
  ru: 'Ruth',

  lamentations: 'Lamentations',
  lam: 'Lamentations',
  lm: 'Lamentations',

  ecclésiastes: 'Ecclésiastes',
  ecclesiastes: 'Ecclésiastes',
  eccl: 'Ecclésiastes',
  ecc: 'Ecclésiastes',
  ec: 'Ecclésiastes',

  esther: 'Esther',
  est: 'Esther',

  daniel: 'Daniel',
  dan: 'Daniel',
  da: 'Daniel',

  esdras: 'Esdras',
  esd: 'Esdras',
  ed: 'Esdras',

  néhémie: 'Néhémie',
  nehemie: 'Néhémie',
  neh: 'Néhémie',
  ne: 'Néhémie',

  '1 chroniques': '1Chroniques',
  '1 chr': '1Chroniques',
  '1 ch': '1Chroniques',
  '1chroniques': '1Chroniques',
  '1chr': '1Chroniques',
  '1ch': '1Chroniques',

  '2 chroniques': '2Chroniques',
  '2 chr': '2Chroniques',
  '2 ch': '2Chroniques',
  '2chroniques': '2Chroniques',
  '2chr': '2Chroniques',
  '2ch': '2Chroniques',

  matthieu: 'Matthieu',
  matt: 'Matthieu',
  mat: 'Matthieu',
  mt: 'Matthieu',

  marc: 'Marc',
  mar: 'Marc',
  mc: 'Marc',

  luc: 'Luc',
  lu: 'Luc',
  lc: 'Luc',

  jean: 'Jean',
  jea: 'Jean',
  jn: 'Jean',

  actes: 'Actes',
  act: 'Actes',
  ac: 'Actes',

  romains: 'Romains',
  rom: 'Romains',
  rm: 'Romains',

  '1 corinthiens': '1Corinthiens',
  '1corinthiens': '1Corinthiens',
  '1 cor': '1Corinthiens',
  '1cor': '1Corinthiens',
  '1 co': '1Corinthiens',
  '1co': '1Corinthiens',

  '2 corinthiens': '2Corinthiens',
  '2corinthiens': '2Corinthiens',
  '2 cor': '2Corinthiens',
  '2cor': '2Corinthiens',
  '2 co': '2Corinthiens',
  '2co': '2Corinthiens',

  galates: 'Galates',
  gal: 'Galates',
  ga: 'Galates',
  gl: 'Galates',

  éphésiens: 'Éphésiens',
  ephesiens: 'Éphésiens',
  eph: 'Éphésiens',
  ep: 'Éphésiens',

  philippiens: 'Philippiens',
  phil: 'Philippiens',
  phi: 'Philippiens',
  ph: 'Philippiens',

  colossiens: 'Colossiens',
  colo: 'Colossiens',
  col: 'Colossiens',
  cl: 'Colossiens',
  co: 'Colossiens',

  '1 thessaloniciens': '1Thessaloniciens',
  '1 thess': '1Thessaloniciens',
  '1 th': '1Thessaloniciens',
  '1thessaloniciens': '1Thessaloniciens',
  '1thess': '1Thessaloniciens',
  '1th': '1Thessaloniciens',

  '2 thessaloniciens': '2Thessaloniciens',
  '2 thess': '2Thessaloniciens',
  '2 th': '2Thessaloniciens',
  '2thessaloniciens': '2Thessaloniciens',
  '2thess': '2Thessaloniciens',
  '2th': '2Thessaloniciens',

  '1 timothée': '1Timothée',
  '1 timothee': '1Timothée',
  '1 tim': '1Timothée',
  '1 tm': '1Timothée',
  '1timothée': '1Timothée',
  '1timothee': '1Timothée',
  '1tim': '1Timothée',
  '1tm': '1Timothée',

  '2 timothée': '2Timothée',
  '2 timothee': '2Timothée',
  '2 tim': '2Timothée',
  '2 tm': '2Timothée',
  '2timothée': '2Timothée',
  '2timothee': '2Timothée',
  '2tim': '2Timothée',
  '2tm': '2Timothée',

  tite: 'Tite',
  tit: 'Tite',
  ti: 'Tite',
  tt: 'Tite',

  philémon: 'Philémon',
  philemon: 'Philémon',
  plm: 'Philémon',
  pm: 'Philémon',
  pl: 'Philémon',

  hébreux: 'Hébreux',
  hebreux: 'Hébreux',
  héb: 'Hébreux',
  heb: 'Hébreux',
  hb: 'Hébreux',

  jacques: 'Jacques',
  jac: 'Jacques',
  ja: 'Jacques',
  jc: 'Jacques',
  jq: 'Jacques',

  '1 pierre': '1Pierre',
  '1 pie': '1Pierre',
  '1 pi': '1Pierre',
  '1pierre': '1Pierre',
  '1pie': '1Pierre',
  '1pi': '1Pierre',

  '2 pierre': '2Pierre',
  '2 pie': '2Pierre',
  '2 pi': '2Pierre',
  '2pierre': '2Pierre',
  '2pie': '2Pierre',
  '2pi': '2Pierre',

  '1 jean': '1Jean',
  '1 jn': '1Jean',
  '1jean': '1Jean',
  '1jn': '1Jean',

  '2 jean': '2Jean',
  '2 jn': '2Jean',
  '2jean': '2Jean',
  '2jn': '2Jean',

  '3 jean': '3Jean',
  '3 jn': '3Jean',
  '3jean': '3Jean',
  '3jn': '3Jean',

  jude: 'Jude',
  jud: 'Jude',
  ju: 'Jude',
  jd: 'Jude',

  apocalypse: 'Apocalypse',
  apoc: 'Apocalypse',
  apo: 'Apocalypse',
  ap: 'Apocalypse'
}

export const bookChapters: Record<BookName, number> = {
  // AT
  Genèse: 50,
  Exode: 40,
  Lévitique: 27,
  Nombres: 36,
  Deutéronome: 34,
  Josué: 24,
  Juges: 21,
  '1Samuel': 31,
  '2Samuel': 24,
  '1Rois': 22,
  '2Rois': 25,
  Ésaïe: 66,
  Jérémie: 52,
  Ezékiel: 48,
  Osée: 14,
  Joël: 3,
  Amos: 9,
  Abdias: 1,
  Jonas: 4,
  Michée: 7,
  Nahum: 3,
  Habaquq: 3,
  Sophonie: 3,
  Aggée: 2,
  Zacharie: 14,
  Malachie: 4,
  Psaumes: 150,
  Proverbes: 31,
  Job: 42,
  Cantiques: 8,
  Ruth: 4,
  Lamentations: 5,
  Ecclésiastes: 12,
  Esther: 10,
  Daniel: 12,
  Esdras: 10,
  Néhémie: 13,
  '1Chroniques': 29,
  '2Chroniques': 36,

  // NT
  Matthieu: 28,
  Marc: 16,
  Luc: 24,
  Jean: 21,
  Actes: 28,
  Romains: 16,
  '1Corinthiens': 16,
  '2Corinthiens': 13,
  Galates: 6,
  Éphésiens: 6,
  Philippiens: 4,
  Colossiens: 4,
  '1Thessaloniciens': 5,
  '2Thessaloniciens': 3,
  '1Timothée': 6,
  '2Timothée': 4,
  Tite: 3,
  Philémon: 1,
  Hébreux: 13,
  Jacques: 5,
  '1Pierre': 5,
  '2Pierre': 3,
  '1Jean': 5,
  '2Jean': 1,
  '3Jean': 1,
  Jude: 1,
  Apocalypse: 22
}


// TODO: Do we still need this?
export const bookOptions = [
  // OT
  // { label: 'ANCIEN TESTAMENT' },
  // { label: 'Pentateuque' },
  { value: 'Genèse', label: 'Genèse' },
  { value: 'Exode', label: 'Exode' },
  { value: 'Lévitique', label: 'Lévitique' },
  { value: 'Nombres', label: 'Nombres' },
  { value: 'Deutéronome', label: 'Deutéronome' },
  // { label: 'Prophètes' },
  { value: 'Josué', label: 'Josué' },
  { value: 'Juges', label: 'Juges' },
  { value: '1Samuel', label: '1 Samuel' },
  { value: '2Samuel', label: '2 Samuel' },
  { value: '1Rois', label: '1 Rois' },
  { value: '2Rois', label: '2 Rois' },
  { value: 'Ésaïe', label: 'Ésaïe' },
  { value: 'Jérémie', label: 'Jérémie' },
  { value: 'Ezékiel', label: 'Ezékiel' },
  { value: 'Osée', label: 'Osée' },
  { value: 'Joël', label: 'Joël' },
  { value: 'Amos', label: 'Amos' },
  { value: 'Abdias', label: 'Abdias' },
  { value: 'Jonas', label: 'Jonas' },
  { value: 'Michée', label: 'Michée' },
  { value: 'Nahum', label: 'Nahum' },
  { value: 'Habaquq', label: 'Habaquq' },
  { value: 'Sophonie', label: 'Sophonie' },
  { value: 'Aggée', label: 'Aggée' },
  { value: 'Zacharie', label: 'Zacharie' },
  { value: 'Malachie', label: 'Malachie' },
  // { label: 'Écrits' },
  { value: 'Psaumes', label: 'Psaumes' },
  { value: 'Proverbes', label: 'Proverbes' },
  { value: 'Job', label: 'Job' },
  { value: 'Cantiques', label: 'Cantique des cantiques' },
  { value: 'Ruth', label: 'Ruth' },
  { value: 'Lamentations', label: 'Lamentations' },
  { value: 'Ecclésiastes', label: 'Ecclésiastes' },
  { value: 'Esther', label: 'Esther' },
  { value: 'Daniel', label: 'Daniel' },
  { value: 'Esdras', label: 'Esdras' },
  { value: 'Néhémie', label: 'Néhémie' },
  { value: '1Chroniques', label: '1 Chroniques' },
  { value: '2Chroniques', label: '2 Chroniques' },

  // NT
  // { label: 'NOUVEAU TESTAMENT' },
  { value: 'Matthieu', label: 'Matthieu' },
  { value: 'Marc', label: 'Marc' },
  { value: 'Luc', label: 'Luc' },
  { value: 'Jean', label: 'Jean' },
  { value: 'Actes', label: 'Actes' },
  { value: 'Romains', label: 'Romains' },
  { value: '1Corinthiens', label: '1 Corinthiens' },
  { value: '2Corinthiens', label: '2 Corinthiens' },
  { value: 'Galates', label: 'Galates' },
  { value: 'Éphésiens', label: 'Éphésiens' },
  { value: 'Philippiens', label: 'Philippiens' },
  { value: 'Colossiens', label: 'Colossiens' },
  { value: '1Thessaloniciens', label: '1 Thessaloniciens' },
  { value: '2Thessaloniciens', label: '2 Thessaloniciens' },
  { value: '1Timothée', label: '1 Timothée' },
  { value: '2Timothée', label: '2 Timothée' },
  { value: 'Tite', label: 'Tite' },
  { value: 'Philémon', label: 'Philémon' },
  { value: 'Hébreux', label: 'Hébreux' },
  { value: 'Jacques', label: 'Jacques' },
  { value: '1Pierre', label: '1 Pierre' },
  { value: '2Pierre', label: '2 Pierre' },
  { value: '1Jean', label: '1 Jean' },
  { value: '2Jean', label: '2 Jean' },
  { value: '3Jean', label: '3 Jean' },
  { value: 'Jude', label: 'Jude' },
  { value: 'Apocalypse', label: 'Apocalypse' }
]

export const bookSectionsOptions = [
  {
    section: 'Pentateuque',
    options: [
      { value: 'Genèse', label: 'Genèse' },
      { value: 'Exode', label: 'Exode' },
      { value: 'Lévitique', label: 'Lévitique' },
      { value: 'Nombres', label: 'Nombres' },
      { value: 'Deutéronome', label: 'Deutéronome' }
    ]
  },
  {
    section: 'Prophètes',
    options: [
      { value: 'Josué', label: 'Josué' },
      { value: 'Juges', label: 'Juges' },
      { value: '1Samuel', label: '1 Samuel' },
      { value: '2Samuel', label: '2 Samuel' },
      { value: '1Rois', label: '1 Rois' },
      { value: '2Rois', label: '2 Rois' },
      { value: 'Ésaïe', label: 'Ésaïe' },
      { value: 'Jérémie', label: 'Jérémie' },
      { value: 'Ezékiel', label: 'Ezékiel' },
      { value: 'Osée', label: 'Osée' },
      { value: 'Joël', label: 'Joël' },
      { value: 'Amos', label: 'Amos' },
      { value: 'Abdias', label: 'Abdias' },
      { value: 'Jonas', label: 'Jonas' },
      { value: 'Michée', label: 'Michée' },
      { value: 'Nahum', label: 'Nahum' },
      { value: 'Habaquq', label: 'Habaquq' },
      { value: 'Sophonie', label: 'Sophonie' },
      { value: 'Aggée', label: 'Aggée' },
      { value: 'Zacharie', label: 'Zacharie' },
      { value: 'Malachie', label: 'Malachie' }
    ]
  },
  {
    section: 'Écrits',
    options: [
      { value: 'Psaumes', label: 'Psaumes' },
      { value: 'Proverbes', label: 'Proverbes' },
      { value: 'Job', label: 'Job' },
      { value: 'Cantiques', label: 'Cantique des cantiques' },
      { value: 'Ruth', label: 'Ruth' },
      { value: 'Lamentations', label: 'Lamentations' },
      { value: 'Ecclésiastes', label: 'Ecclésiastes' },
      { value: 'Esther', label: 'Esther' },
      { value: 'Daniel', label: 'Daniel' },
      { value: 'Esdras', label: 'Esdras' },
      { value: 'Néhémie', label: 'Néhémie' },
      { value: '1Chroniques', label: '1 Chroniques' },
      { value: '2Chroniques', label: '2 Chroniques' },
    ]
  },
  {
    section: 'Nouveau Testament',
    options: [
      { value: 'Matthieu', label: 'Matthieu' },
      { value: 'Marc', label: 'Marc' },
      { value: 'Luc', label: 'Luc' },
      { value: 'Jean', label: 'Jean' },
      { value: 'Actes', label: 'Actes' },
      { value: 'Romains', label: 'Romains' },
      { value: '1Corinthiens', label: '1 Corinthiens' },
      { value: '2Corinthiens', label: '2 Corinthiens' },
      { value: 'Galates', label: 'Galates' },
      { value: 'Éphésiens', label: 'Éphésiens' },
      { value: 'Philippiens', label: 'Philippiens' },
      { value: 'Colossiens', label: 'Colossiens' },
      { value: '1Thessaloniciens', label: '1 Thessaloniciens' },
      { value: '2Thessaloniciens', label: '2 Thessaloniciens' },
      { value: '1Timothée', label: '1 Timothée' },
      { value: '2Timothée', label: '2 Timothée' },
      { value: 'Tite', label: 'Tite' },
      { value: 'Philémon', label: 'Philémon' },
      { value: 'Hébreux', label: 'Hébreux' },
      { value: 'Jacques', label: 'Jacques' },
      { value: '1Pierre', label: '1 Pierre' },
      { value: '2Pierre', label: '2 Pierre' },
      { value: '1Jean', label: '1 Jean' },
      { value: '2Jean', label: '2 Jean' },
      { value: '3Jean', label: '3 Jean' },
      { value: 'Jude', label: 'Jude' },
      { value: 'Apocalypse', label: 'Apocalypse' }
    ]
  }
]
